"""Build GTSRB-C: the held-out GTSRB test set under synthetic input corruption.

This is the dataset the inference-time half of the project is measured on. It
is written to disk as ordinary PNG trees, one directory per condition, each of
them a valid `ImageFolder` root - so evaluating a model on a corruption needs no
new loading code at all, only a different path.

    dataset/gtsrb_c/
        clean/                00000/ ... 00042/
        fog_s1/               00000/ ... 00042/
        fog_s3/               00000/ ... 00042/
        gaussian_noise_s1/    ...
        manifest.json

Run it with:

    python -m iot.gtsrb_c --dry-run          # show the plan, write nothing
    python -m iot.gtsrb_c                    # build with the defaults below


Three decisions are baked in here, and each one is load-bearing.

**Resize first, then corrupt.** `imagecorruptions` rejects any image with a side
under 32 px, and roughly one GTSRB test image in five is smaller than that
natively (the median is 43x44, the smallest 26x25). Corrupting at native
resolution is therefore not an option that exists. The consequence is worth
stating plainly in any write-up: noise applied after an upscale lands on pixels
that are already interpolated, so this is not the same thing as a genuinely
low-resolution camera feed. Every benchmark in this family - CIFAR-10-C most of
all - has the same caveat.

**"clean" is a condition, generated by the same code path.** It costs a copy of
the images and it removes a whole class of confound. Read from the original
files instead, the clean images would reach the network through torchvision's
`Resize` while the corrupted ones came through this module's - two different
interpolations, and a difference between "clean" and "corrupted" that is not
the corruption. Here every condition passes through one identical resize, so
the corruption is the only variable. For the same reason the filter is
BILINEAR: that is what `transforms.Resize` uses by default in
`model_manager.py:64`, where the model was trained.

**One subsample, shared by every condition.** The same images appear in every
condition, so comparing two corruptions is a paired comparison and sampling
noise cancels out instead of being mistaken for an effect.

A note on how many images that needs to be. The GTSRB test set looks like 12630
independent samples and is not: every per-class count is an exact multiple of
30, and 12630 / 30 = 421, so it is 421 physical signs photographed 30 times
each - the same track structure as the training set, with the track ids
stripped from the filenames. Thirty frames of one sign are near-duplicates, so
the effective sample size is closer to 421 than to 12630 and a confidence
interval computed on the image count is roughly five times too narrow.
Subsampling therefore costs far less than it appears to, and the default of
2000 images per condition is not the accuracy bottleneck - 421 signs is.
"""

import argparse
import hashlib
import json
import multiprocessing
import os
import platform
import sys
import time
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

import numpy as np
from PIL import Image

# Import through the shim, never straight from `imagecorruptions`: three
# corruptions raise at call time on a modern numpy / scikit-image without it.
from iot.corruption_shim import MIN_SIDE_PX, corrupt, corruption_names, patch_report

# --- the corruption set -----------------------------------------------------
#
# Split into two groups that the adaptation stage treats very differently.
# SEEN are the corruptions a bank of specialized normalization states may be
# built from. UNSEEN are never in that bank: they exist to measure whether the
# routing degrades gracefully on a degradation it has never been shown, which
# is the honest question to ask of any method that matches against a catalogue.
#
# The four families below are the standard ImageNet-C grouping.

CORRUPTIONS_SEEN: Tuple[str, ...] = (
    # noise
    'gaussian_noise', 'shot_noise', 'impulse_noise',
    # blur
    'defocus_blur', 'motion_blur', 'zoom_blur',
    # weather
    'snow', 'frost', 'fog',
    # digital
    'contrast', 'pixelate', 'jpeg_compression',
)

# Three of these belong to families the bank does cover, so they ask whether an
# unfamiliar degradation can be mapped onto a sensible relative. The fourth,
# elastic_transform, is a geometric warp: no mechanism in the bank resembles it,
# and it is included precisely so the method has somewhere to fail visibly.
CORRUPTIONS_UNSEEN: Tuple[str, ...] = (
    'speckle_noise',      # noise family, present in the bank
    'gaussian_blur',      # blur family, present in the bank
    'brightness',         # photometric, family present
    'elastic_transform',  # geometric warp, nothing like it in the bank
)

DEFAULT_CORRUPTIONS: Tuple[str, ...] = CORRUPTIONS_SEEN + CORRUPTIONS_UNSEEN

# Available but off by default, with the reason, so that the choice is a
# decision on record rather than an oversight.
NOT_IN_DEFAULT_SET: Dict[str, str] = {
    'glass_blur': 'costs 389 ms/image, ~5x the other eighteen combined',
    'spatter': 'adds nothing the weather group does not already cover',
    'saturate': 'adds nothing the digital group does not already cover',
}

DEFAULT_SEVERITIES: Tuple[int, ...] = (1, 3, 5)
DEFAULT_PER_CONDITION = 2000
DEFAULT_IMAGE_SIZE = 128
DEFAULT_SEED = 42
CLEAN_CONDITION = 'clean'

RESAMPLING = Image.Resampling.BILINEAR


# --- naming and seeding -----------------------------------------------------

def condition_name(corruption: str, severity: int) -> str:
    """Directory name for one (corruption, severity) pair."""
    return f"{corruption}_s{severity}"


def derive_seed(*parts) -> int:
    """A stable 32-bit seed from arbitrary parts.

    Deliberately not Python's `hash()`: that is salted per process, so a
    dataset generated across several worker processes would differ from one
    generated in a single process, and differ again on the next run. blake2b
    gives the same number everywhere and forever, which is what makes the whole
    dataset regenerable from the manifest instead of having to be copied
    between machines.
    """
    digest = hashlib.blake2b(digest_size=8)
    for part in parts:
        digest.update(str(part).encode('utf-8'))
        digest.update(b'\x00')
    return int.from_bytes(digest.digest(), 'big') % (2 ** 32 - 1)


# --- subsampling ------------------------------------------------------------

def _class_index(source_dir: Path) -> Dict[str, List[str]]:
    """Class directory -> sorted list of image filenames."""
    index = {}
    for entry in sorted(source_dir.iterdir()):
        if not entry.is_dir():
            continue
        names = sorted(p.name for p in entry.iterdir()
                       if p.suffix.lower() in ('.png', '.ppm', '.jpg', '.jpeg'))
        if names:
            index[entry.name] = names
    if not index:
        raise FileNotFoundError(f"No class directories with images under {source_dir}")
    return index


def _allocate(counts: Dict[str, int], size: int) -> Dict[str, int]:
    """Split `size` across classes in proportion to `counts`.

    Largest-remainder, so the parts add up to exactly `size` instead of
    drifting by a few images. Every non-empty class keeps at least one image:
    GTSRB's rarest test class holds 60 of 12630, and a plain floor would drop
    it entirely at small sample sizes, which would quietly change what the
    weighted F1 is averaging over.
    """
    classes = sorted(counts)
    total = sum(counts.values())
    if size >= total:
        return dict(counts)

    exact = {c: size * counts[c] / total for c in classes}
    alloc = {c: min(counts[c], max(1, int(exact[c]))) for c in classes}

    # Hand out, or claw back, whatever the flooring and the clamp left over.
    remainder = size - sum(alloc.values())
    if remainder > 0:
        # Largest fractional part first; ties broken by class name so the
        # result does not depend on dictionary order.
        order = sorted(classes, key=lambda c: (-(exact[c] - int(exact[c])), c))
        for c in order:
            if remainder == 0:
                break
            if alloc[c] < counts[c]:
                alloc[c] += 1
                remainder -= 1
    elif remainder < 0:
        order = sorted(classes, key=lambda c: (-alloc[c], c))
        for c in order:
            if remainder == 0:
                break
            if alloc[c] > 1:
                alloc[c] -= 1
                remainder += 1
    return alloc


def stratified_subsample(source_dir: Path, size: int, seed: int) -> Dict[str, List[str]]:
    """Pick `size` images, keeping each class's share of the whole.

    The draw is seeded per class rather than from one shared stream, so the
    selection for a class does not depend on how many classes were processed
    before it.
    """
    index = _class_index(source_dir)
    alloc = _allocate({c: len(v) for c, v in index.items()}, size)

    chosen = {}
    for class_dir, names in index.items():
        k = alloc[class_dir]
        rng = np.random.default_rng(derive_seed(seed, 'subsample', class_dir))
        picks = rng.choice(len(names), size=k, replace=False)
        chosen[class_dir] = [names[i] for i in sorted(picks)]
    return chosen


# --- generation -------------------------------------------------------------

_CTX: dict = {}


def _init_worker(source_dir, output_dir, image_size, conditions, seed):
    _CTX.update(source_dir=Path(source_dir), output_dir=Path(output_dir),
                image_size=image_size, conditions=conditions, seed=seed)


def _save_png(image: Image.Image, path: Path) -> None:
    # compress_level is Pillow's default, stated explicitly because the whole
    # point of the seeding above is byte-for-byte regeneration.
    image.save(path, format='PNG', compress_level=6)


def _process_one(task: Tuple[str, str]) -> Tuple[str, str]:
    """Every condition for a single source image.

    Decoding and resizing happen once here rather than once per condition,
    which is the only reason a full build is minutes rather than hours.
    """
    class_dir, filename = task
    ctx = _CTX
    size = ctx['image_size']

    with Image.open(ctx['source_dir'] / class_dir / filename) as handle:
        base = handle.convert('RGB').resize((size, size), RESAMPLING)
    array = np.asarray(base)

    stem = Path(filename).stem + '.png'
    _save_png(base, ctx['output_dir'] / CLEAN_CONDITION / class_dir / stem)

    relative = f"{class_dir}/{filename}"
    for corruption, severity in ctx['conditions']:
        # Several corruptions draw from numpy's global RNG. Seeding per
        # (image, corruption, severity) - not once per process - is what makes
        # the output independent of the number of workers and of the order the
        # pool happens to hand out tasks.
        np.random.seed(derive_seed(ctx['seed'], relative, corruption, severity))
        corrupted = corrupt(array, corruption_name=corruption, severity=severity)
        _save_png(Image.fromarray(corrupted),
                  ctx['output_dir'] / condition_name(corruption, severity) / class_dir / stem)
    return task


def plan(corruptions: Sequence[str], severities: Sequence[int]) -> List[Tuple[str, int]]:
    return [(c, s) for c in corruptions for s in severities]


def build(source_dir: Path, output_dir: Path,
          corruptions: Sequence[str] = DEFAULT_CORRUPTIONS,
          severities: Sequence[int] = DEFAULT_SEVERITIES,
          per_condition: int = DEFAULT_PER_CONDITION,
          image_size: int = DEFAULT_IMAGE_SIZE,
          seed: int = DEFAULT_SEED,
          jobs: int = 0,
          progress: bool = True) -> dict:
    """Generate the whole corrupted dataset and return the manifest."""
    source_dir, output_dir = Path(source_dir), Path(output_dir)
    conditions = plan(corruptions, severities)
    subsample = stratified_subsample(source_dir, per_condition, seed)
    tasks = [(c, name) for c in sorted(subsample) for name in subsample[c]]

    # Every directory up front, in the parent: workers that create them
    # concurrently race on the same paths.
    for condition in [CLEAN_CONDITION] + [condition_name(c, s) for c, s in conditions]:
        for class_dir in subsample:
            (output_dir / condition / class_dir).mkdir(parents=True, exist_ok=True)

    jobs = jobs or os.cpu_count() or 1
    started = time.time()
    args = (str(source_dir), str(output_dir), image_size, conditions, seed)

    if jobs == 1:
        _init_worker(*args)
        for done, task in enumerate(map(_process_one, tasks), 1):
            if progress and done % 200 == 0:
                _report_progress(done, len(tasks), started)
    else:
        with multiprocessing.Pool(jobs, initializer=_init_worker, initargs=args) as pool:
            for done, _ in enumerate(pool.imap_unordered(_process_one, tasks, chunksize=8), 1):
                if progress and done % 200 == 0:
                    _report_progress(done, len(tasks), started)

    manifest = {
        'created': time.strftime('%Y-%m-%dT%H:%M:%S'),
        'source_dir': str(source_dir),
        'seed': seed,
        'image_size': image_size,
        'resampling': 'BILINEAR',
        'per_condition': per_condition,
        'images_per_class': {c: len(v) for c, v in sorted(subsample.items())},
        'total_images_per_condition': len(tasks),
        'severities': list(severities),
        'corruptions_seen': [c for c in corruptions if c in CORRUPTIONS_SEEN],
        'corruptions_unseen': [c for c in corruptions if c in CORRUPTIONS_UNSEEN],
        'corruptions_other': [c for c in corruptions
                              if c not in CORRUPTIONS_SEEN and c not in CORRUPTIONS_UNSEEN],
        'conditions': [CLEAN_CONDITION] + [condition_name(c, s) for c, s in conditions],
        'shim_applied': patch_report(),
        'versions': _versions(),
        'build_seconds': round(time.time() - started, 1),
    }
    (output_dir / 'manifest.json').write_text(json.dumps(manifest, indent=2))
    return manifest


def _report_progress(done: int, total: int, started: float) -> None:
    elapsed = time.time() - started
    rate = done / elapsed if elapsed else 0
    eta = (total - done) / rate if rate else 0
    print(f"  {done}/{total} images  |  {rate:.1f} img/s  |  eta {eta / 60:.1f} min", flush=True)


def _package_version(name: str) -> str:
    """The installed version of a package, whether or not it exposes one.

    `imagecorruptions` has no `__version__` attribute, and it is the single most
    important version in this manifest: it decides what the corruptions actually
    do. Ask the installed distribution metadata rather than the module, which is
    also the only thing that works for a package installed from a wheel with no
    attribute at all.
    """
    try:
        from importlib.metadata import PackageNotFoundError, version
        return version(name)
    except Exception:
        module = sys.modules.get(name)
        return str(getattr(module, '__version__', 'unknown'))


def _versions() -> Dict[str, str]:
    import skimage  # noqa: F401  (imported for the metadata lookup below)
    import imagecorruptions  # noqa: F401
    return {
        'python': platform.python_version(),
        'numpy': np.__version__,
        'scikit-image': _package_version('scikit-image'),
        'imagecorruptions': _package_version('imagecorruptions'),
        'pillow': _package_version('pillow'),
    }


# --- CLI --------------------------------------------------------------------

def _estimate(n_images: int, n_conditions: int, image_size: int) -> str:
    # 17.3 KB is the measured mean for a 128x128 GTSRB PNG; scaled by area for
    # any other size, which is close enough for a sanity check.
    kb = 17.3 * (image_size / 128) ** 2
    return f"{kb * n_images * n_conditions / 1e6:.1f} GB"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description='Build GTSRB-C, the corrupted GTSRB test set.')
    parser.add_argument('--source', default='dataset/gtsrb/test',
                        help='class-per-directory tree to corrupt (default: %(default)s)')
    parser.add_argument('--output', default='dataset/gtsrb_c',
                        help='where to write the conditions (default: %(default)s)')
    parser.add_argument('--per-condition', type=int, default=DEFAULT_PER_CONDITION,
                        help='images per condition, stratified by class (default: %(default)s)')
    parser.add_argument('--severities', type=int, nargs='+', default=list(DEFAULT_SEVERITIES))
    parser.add_argument('--image-size', type=int, default=DEFAULT_IMAGE_SIZE,
                        help='must match the training pipeline (default: %(default)s)')
    parser.add_argument('--seed', type=int, default=DEFAULT_SEED)
    parser.add_argument('--jobs', type=int, default=0, help='0 = one per core')
    parser.add_argument('--corruptions', nargs='+', default=None,
                        help='override the default set; "all" for everything installed')
    parser.add_argument('--dry-run', action='store_true',
                        help='print the plan and write nothing')
    args = parser.parse_args(argv)

    if args.corruptions == ['all']:
        corruptions = corruption_names()
    elif args.corruptions:
        corruptions = args.corruptions
    else:
        corruptions = list(DEFAULT_CORRUPTIONS)

    unknown = sorted(set(corruptions) - set(corruption_names()))
    if unknown:
        parser.error(f"unknown corruption(s): {', '.join(unknown)}")
    if args.image_size < MIN_SIDE_PX:
        parser.error(f"--image-size must be at least {MIN_SIDE_PX} "
                     f"(imagecorruptions rejects anything smaller)")

    source = Path(args.source)
    if not source.is_dir():
        parser.error(f"source directory not found: {source}")

    conditions = plan(corruptions, args.severities)
    subsample = stratified_subsample(source, args.per_condition, args.seed)
    n_images = sum(len(v) for v in subsample.values())
    n_conditions = len(conditions) + 1

    print(f"source        {source}")
    print(f"output        {args.output}")
    print(f"corruptions   {len(corruptions)} "
          f"({sum(c in CORRUPTIONS_SEEN for c in corruptions)} seen, "
          f"{sum(c in CORRUPTIONS_UNSEEN for c in corruptions)} unseen)")
    print(f"severities    {args.severities}")
    print(f"conditions    {n_conditions} (including '{CLEAN_CONDITION}')")
    print(f"images        {n_images} per condition, {len(subsample)} classes")
    print(f"total files   {n_images * n_conditions}  (~{_estimate(n_images, n_conditions, args.image_size)})")
    print(f"shim applied  {patch_report()}")

    if args.dry_run:
        print("\n-- dry run, nothing written --")
        return 0

    print()
    manifest = build(source, Path(args.output), corruptions, args.severities,
                     args.per_condition, args.image_size, args.seed, args.jobs)
    print(f"\nDone in {manifest['build_seconds'] / 60:.1f} min -> {args.output}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
